import type { WeatherInfo } from "@/types/weather";

export const dummyForecast: WeatherInfo[] = [
  {
    id: 1,
    weather: 'CLEAR',
    description: '맑음',
    dailyTemperatureGap: 9,
    feelsLikeTemperature: 33,
    maxTemperature: 35,
    minTemperature: 26,
    pop: 0.0,
    rain: 0.0,
    snow: 0.0,
    humidity: 38,
    windSpeed: 2.4,
    windDeg: 110,
    uvi: 7.6,
    location: '서울',
    date: '2025-07-29',
  },
  {
    id: 2,
    weather: 'CLOUDS',
    description: '흐림',
    dailyTemperatureGap: 6,
    feelsLikeTemperature: 31,
    maxTemperature: 32,
    minTemperature: 26,
    pop: 0.1,
    rain: 0.2,
    snow: 0.0,
    humidity: 55,
    windSpeed: 3.1,
    windDeg: 95,
    uvi: 5.8,
    location: '서울',
    date: '2025-07-30',
  },
  {
    id: 3,
    weather: 'RAIN',
    description: '비',
    dailyTemperatureGap: 5,
    feelsLikeTemperature: 28,
    maxTemperature: 30,
    minTemperature: 25,
    pop: 0.9,
    rain: 6.2,
    snow: 0.0,
    humidity: 84,
    windSpeed: 4.3,
    windDeg: 180,
    uvi: 2.2,
    location: '서울',
    date: '2025-07-31',
  },
  {
    id: 4,
    weather: 'DRIZZLE',
    description: '이슬비',
    dailyTemperatureGap: 4,
    feelsLikeTemperature: 29,
    maxTemperature: 31,
    minTemperature: 27,
    pop: 0.6,
    rain: 2.1,
    snow: 0.0,
    humidity: 70,
    windSpeed: 3.7,
    windDeg: 150,
    uvi: 3.9,
    location: '서울',
    date: '2025-08-01',
  },
  {
    id: 5,
    weather: 'SNOW',
    description: '눈',
    dailyTemperatureGap: 10,
    feelsLikeTemperature: -2,
    maxTemperature: 1,
    minTemperature: -9,
    pop: 0.3,
    rain: 0.0,
    snow: 5.6,
    humidity: 60,
    windSpeed: 5.0,
    windDeg: 200,
    uvi: 1.1,
    location: '서울',
    date: '2025-08-02',
  },
  {
    id: 6,
    weather: 'ATMOSPHERE',
    description: '안개',
    dailyTemperatureGap: 3,
    feelsLikeTemperature: 26,
    maxTemperature: 28,
    minTemperature: 25,
    pop: 0.2,
    rain: 0.0,
    snow: 0.0,
    humidity: 90,
    windSpeed: 1.5,
    windDeg: 60,
    uvi: 1.5,
    location: '서울',
    date: '2025-08-03',
  },
  {
    id: 7,
    weather: 'THUNDERSTORM',
    description: '천둥번개',
    dailyTemperatureGap: 7,
    feelsLikeTemperature: 30,
    maxTemperature: 31,
    minTemperature: 24,
    pop: 0.95,
    rain: 12.4,
    snow: 0.0,
    humidity: 88,
    windSpeed: 6.8,
    windDeg: 230,
    uvi: 3.0,
    location: '서울',
    date: '2025-08-04',
  },
];
